### ISSUE TITLE
Specs missing

### ISSUE THREAD

**Issue by fvanwijk** [jillesme/safe-object#1]
Suppose you have:

``` js
var obj = { 
    user: {
        name: 'Jilles',
        demo: true
    }
}
```

`so(obj, 'user.name')` returns `Jilles`, but `so(obj, 'user.name.xxx')` also returns `Jilles`. It should return `undefined` right?

Update: Sorry it works. Forgot to save my example file.. It was not updating the result :)
However, you should add specs.

**Comment by jillesme** [comment]
I definitely agree on the specs, feel free to create a PR. Rumour has it you're the test god with [mox](https://github.com/fvanwijk/mox)

**Comment by fvanwijk** [comment]
Sure, but Mox without Angular is like Frank without Jilles.
I'll create a PR with some vanilla Mocha specs when I've got time.

**Comment by jillesme** [comment]
:+1: !
